/**
 * SPEECH SYNTHESIZER — Text to speech
 * ===================================
 * Converts the text generated by Broca's area into spoken audio.
 *
 * Uses the Web Speech API (SpeechSynthesis) when running in the
 * browser. In Node.js, it generates commands for external TTS.
 *
 * Biology: Broca's area controls speech production.
 * Rate, pitch and volume are modulated by the emotional state.
 */

import type { EmotionalState } from './emotion-decoder.js';

/** Speech synthesis configuration */
export interface SpeechConfig {
  /** Language (BCP 47 code) */
  lang: string;
  /** Base speech rate (0.1-10, 1 = normal) */
  rate: number;
  /** Base pitch (0-2, 1 = normal) */
  pitch: number;
  /** Volume (0-1) */
  volume: number;
}

const DEFAULT_SPEECH_CONFIG: SpeechConfig = {
  lang: 'es-ES',
  rate: 1.0,
  pitch: 1.0,
  volume: 0.8,
};

/**
 * Speech synthesizer that modulates parameters according to emotional state.
 */
export class SpeechSynthesizer {
  private config: SpeechConfig;
  /** History of generated utterances */
  private history: Array<{ text: string; timestamp: number; emotion?: string }> = [];

  constructor(config: Partial<SpeechConfig> = {}) {
    this.config = { ...DEFAULT_SPEECH_CONFIG, ...config };
  }

  /**
   * Generates speech parameters modulated by emotion.
   * In the browser, this would feed SpeechSynthesisUtterance.
   *
   * @param text - Text to speak
   * @param emotion - Current emotional state (optional)
   * @returns Adjusted speech parameters
   */
  synthesize(text: string, emotion?: EmotionalState): {
    text: string;
    rate: number;
    pitch: number;
    volume: number;
    lang: string;
    ssml?: string;
  } {
    let rate = this.config.rate;
    let pitch = this.config.pitch;
    let volume = this.config.volume;

    if (emotion) {
      // Modulate rate according to arousal
      // High arousal → faster speech
      rate *= (0.8 + emotion.arousal * 0.6);

      // Modulate pitch according to valence
      // Positive → higher pitch, Negative → lower pitch
      pitch *= (0.85 + (emotion.valence + 1) * 0.15);

      // Modulate volume according to intensity
      volume = Math.min(1, volume * (0.7 + emotion.intensity * 0.5));
    }

    // Clamp ranges
    rate = Math.max(0.5, Math.min(2.0, rate));
    pitch = Math.max(0.5, Math.min(2.0, pitch));
    volume = Math.max(0.1, Math.min(1.0, volume));

    // Record in history
    this.history.push({
      text,
      timestamp: Date.now(),
      emotion: emotion?.primaryEmotion,
    });

    // Generate SSML for fine-grained control (if the TTS supports it)
    const ssml = this.generateSSML(text, rate, pitch, volume);

    return { text, rate, pitch, volume, lang: this.config.lang, ssml };
  }

  /**
   * Generates SSML (Speech Synthesis Markup Language) for precise control.
   */
  private generateSSML(text: string, rate: number, pitch: number, volume: number): string {
    const ratePercent = Math.round(rate * 100);
    const pitchPercent = Math.round((pitch - 1) * 100);
    const pitchStr = pitchPercent >= 0 ? `+${pitchPercent}%` : `${pitchPercent}%`;

    return `<speak>
  <prosody rate="${ratePercent}%" pitch="${pitchStr}" volume="${Math.round(volume * 100)}">
    ${this.escapeSSML(text)}
  </prosody>
</speak>`;
  }

  /**
   * Escapes special characters for SSML.
   */
  private escapeSSML(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  /**
   * Generates the TTS command for Node.js (macOS `say` command).
   */
  generateNodeCommand(text: string, emotion?: EmotionalState): string {
    const params = this.synthesize(text, emotion);
    // macOS `say` command
    const rateWPM = Math.round(params.rate * 175); // 175 WPM is normal speed
    return `say -r ${rateWPM} "${text.replace(/"/g, '\\"')}"`;
  }

  /** Returns the history of utterances */
  getHistory(): typeof this.history {
    return [...this.history];
  }

  /** Clears the history */
  clearHistory(): void {
    this.history = [];
  }
}
