/**
 * BROCA'S AREA — Language Production
 * =========================================
 * Models Broca's area (pars opercularis and pars triangularis of the inferior
 * frontal gyrus, Brodmann areas 44/45) of the digital brain,
 * responsible for speech production and planning.
 *
 * Biological basis:
 *   Broca's area was discovered by Paul Broca in 1861 while studying
 *   the patient "Tan" (Louis Leborgne), who could only pronounce the
 *   syllable "tan" after a lesion in the left inferior frontal gyrus.
 *   "Broca's aphasia" (expressive/non-fluent aphasia) is characterized
 *   by preserved comprehension but severely reduced verbal production
 *   and agrammatism (telegraphic speech).
 *
 *   Modeled functions:
 *   1. **Articulatory planning**: Translates semantic representations
 *      (communicative intention from the prefrontal cortex) into sequences
 *      of speech motor patterns.
 *
 *   2. **Lexical selection for production**: Searches the shared lexicon
 *      for the words that best express the semantic intention. Unlike
 *      Wernicke (which receives input and searches for meaning), Broca
 *      starts from meaning and searches for form (inverted lexical access).
 *
 *   3. **Sequencing**: Orders the selected lexical patterns into
 *      a temporally correct sequence (simplified syntax).
 *
 *   4. **Emotional modulation**: The emotional state (valence/arousal from
 *      the amygdala) modifies prosody and lexical selection, modeling
 *      how emotions affect speech (e.g.: more reduced vocabulary
 *      under high stress).
 *
 *   Connections:
 *   - Receives: semantic intention from the prefrontal cortex (via
 *     fronto-frontal fibers) and emotional state from the amygdala
 *   - Sends: speech motor patterns to the primary motor cortex
 *   - Shares: lexicon with Wernicke's area (via the arcuate fasciculus)
 */

import { BrainRegion } from '../../core/brain-region.js';
import type { ModulationEffects } from '../../core/neuromodulators/modulator-system.js';
import { Lexicon, type LexiconMatch } from './lexicon.js';

/**
 * Activation floor for the k-WTA. The potentials are sums of dimensionless
 * weights (~0 at rest), not mV. Without this floor the gate compares against
 * `_modulatedThreshold` (−55 mV), always passes, and the k-WTA fires k neurons
 * per tick → constant and false activity. With the floor, it stays at 0% at rest.
 */
const ACTIVATION_FLOOR = 1e-3;

// ==================================================================
// Interfaces
// ==================================================================

/**
 * Emotional state that modulates language production.
 *
 * Biological basis:
 *   The amygdala projects to Broca's area, modulating prosody
 *   (emotional intonation) and lexical selection. High arousal
 *   reduces verbal fluency; positive valence biases toward
 *   positive vocabulary (mood-congruent lexical access).
 */
export interface EmotionalState {
  /**
   * Emotional valence (-1.0 = very negative, +1.0 = very positive).
   * Affects word selection and the tone of the response.
   */
  valence: number;
  /**
   * Emotional arousal level (0.0 = calm, 1.0 = high excitation).
   * Affects the length and complexity of the response: high arousal
   * produces shorter and less elaborate responses.
   */
  arousal: number;
}

/**
 * Word selected for production with its relevance score.
 */
export interface SelectedWord {
  /** Word selected from the lexicon */
  word: string;
  /** Semantic relevance score (0.0–1.0) */
  relevance: number;
  /** Associated neural pattern in the lexicon */
  pattern: Float32Array;
}

/**
 * Linguistic response generated by Broca's area.
 */
export interface LanguageResponse {
  /** Sequence of speech motor patterns (one per word) */
  wordPatterns: Float32Array[];
  /** Selected words in order */
  words: string[];
  /** Overall confidence in the response (0.0–1.0) */
  confidence: number;
}

// ==================================================================
// BrocaArea class
// ==================================================================

/**
 * Broca's area — Linguistic production of the digital brain.
 *
 * Receives semantic intentions from the prefrontal cortex, selects
 * words from the shared lexicon by cosine similarity, and generates a
 * sequence of speech motor patterns modulated by the emotional state.
 *
 * Biological basis:
 *   The cortical columns in the inferior frontal gyrus specialize
 *   in sequencing complex motor patterns. The internal SNN
 *   models the competition between lexical candidates during
 *   production (competitive lexical selection model,
 *   Levelt et al., 1999). Lateral inhibition ensures that only
 *   one word is selected per temporal slot.
 */
export class BrocaArea extends BrainRegion {
  /**
   * Lexicon shared with Wernicke's area.
   *
   * Biology: Broca accesses the same lexical store as Wernicke but
   * via the dorsal pathway (arcuate fasciculus): it searches for the
   * lexical form starting from meaning (the reverse direction of comprehension).
   */
  private readonly lexicon: Lexicon;

  /**
   * Last generated linguistic response.
   */
  private lastResponse: LanguageResponse | null = null;

  /**
   * Maximum number of words per response.
   *
   * Biology: The length of verbal utterances is limited by
   * articulatory planning capacity and phonological working
   * memory (Baddeley's phonological loop, ~2 seconds of speech).
   */
  private readonly maxResponseLength: number = 10;

  /**
   * Creates Broca's area of the digital brain.
   *
   * Biology: Broca's area contains ~100 million neurons in
   * areas 44/45. We model 5,000 neurons with 5,000 inputs,
   * reflecting the columnar structure of the inferior frontal gyrus.
   *
   * @param lexicon - Shared lexicon (same instance as Wernicke)
   */
  constructor(lexicon: Lexicon, neuronCount: number = 5000, inputCount: number = 5000) {
    super(
      'broca',
      'Área de Broca — Producción del Lenguaje',
      neuronCount,
      inputCount
    );
    this.lexicon = lexicon;
  }

  // ----------------------------------------------------------------
  // Lexical Selection
  // ----------------------------------------------------------------

  /**
   * Selects the K most relevant words to express a semantic pattern.
   *
   * Biological basis:
   *   Models lexical access for production (lemmatization): given a
   *   semantic concept, it searches for the lexical form that best expresses it.
   *   Selection occurs by competition: multiple lemmas are partially
   *   activated and compete for selection (WEAVER++ model, Levelt
   *   et al., 1999). The words with the highest cosine similarity to
   *   the intention pattern win the competition.
   *
   * @param semanticPattern - Semantic pattern of the communicative intention
   * @param topK - Number of words to select
   * @returns Selected words ordered by descending relevance
   */
  selectWords(semanticPattern: Float32Array, topK: number = 5): SelectedWord[] {
    if (this.lexicon.size === 0) return [];

    const matches: LexiconMatch[] = this.lexicon.findClosest(semanticPattern, topK);

    return matches.map(m => {
      const pattern = this.lexicon.lookup(m.word);
      return {
        word: m.word,
        relevance: m.similarity,
        pattern: pattern ? new Float32Array(pattern) : new Float32Array(this.lexicon.dimensions),
      };
    });
  }

  // ----------------------------------------------------------------
  // Response Generation
  // ----------------------------------------------------------------

  /**
   * Generates a linguistic response from a semantic intention
   * and an emotional state.
   *
   * Biological basis:
   *   Speech production in Broca follows a 3-stage pipeline
   *   (Levelt's model, 1989):
   *
   *   1. **Conceptualization** → received as intention from the PFC
   *   2. **Formulation** → lexical selection + grammatical encoding
   *   3. **Articulation** → generation of motor patterns
   *
   *   The emotional state modulates formulation:
   *   - High arousal → shorter responses (anxiety reduces verbal
   *     fluency, Yerkes-Dodson effect in production)
   *   - Negative valence → bias toward high-frequency words
   *     ("safe" vocabulary under stress)
   *   - Positive valence → greater lexical diversity
   *
   * @param intention - Semantic pattern of the communicative intention (from the PFC)
   * @param emotionalState - Current emotional state (from the amygdala)
   * @returns Linguistic response with a sequence of patterns and words
   */
  generateResponse(
    intention: Float32Array,
    emotionalState: EmotionalState
  ): LanguageResponse {
    // 1. Determine the response length based on arousal
    //    High arousal → shorter response (effect of stress on fluency)
    const arousalFactor = 1.0 - emotionalState.arousal * 0.6;
    const responseLength = Math.max(
      1,
      Math.floor(this.maxResponseLength * arousalFactor)
    );

    // 2. Determine the number of candidates to evaluate based on valence
    //    Positive valence → more candidates → greater diversity
    const diversityFactor = 1.0 + Math.max(0, emotionalState.valence) * 0.5;
    const candidateCount = Math.ceil(responseLength * diversityFactor * 2);

    // 3. Select lexical candidates
    const candidates = this.selectWords(intention, candidateCount);

    if (candidates.length === 0) {
      return { wordPatterns: [], words: [], confidence: 0 };
    }

    // 4. Build the response sequence
    const wordPatterns: Float32Array[] = [];
    const words: string[] = [];
    let totalRelevance = 0;

    // Select the best words without repeating
    const used = new Set<string>();

    for (const candidate of candidates) {
      if (words.length >= responseLength) break;
      if (used.has(candidate.word)) continue;

      // Under negative valence, favor high-relevance words
      // (more conservative vocabulary under stress)
      const valencePenalty = emotionalState.valence < 0
        ? (1.0 - candidate.relevance) * Math.abs(emotionalState.valence) * 0.3
        : 0;

      if (candidate.relevance - valencePenalty > 0.05) {
        words.push(candidate.word);
        wordPatterns.push(candidate.pattern);
        totalRelevance += candidate.relevance;
        used.add(candidate.word);
      }
    }

    const confidence = words.length > 0 ? totalRelevance / words.length : 0;

    const response: LanguageResponse = {
      wordPatterns,
      words,
      confidence,
    };

    this.lastResponse = response;
    return response;
  }

  /**
   * Returns the last generated linguistic response.
   */
  getLastResponse(): LanguageResponse | null {
    return this.lastResponse;
  }

  /**
   * Returns a reference to the shared lexicon.
   */
  getLexicon(): Lexicon {
    return this.lexicon;
  }

  // ----------------------------------------------------------------
  // processInput — Linguistic production cycle
  // ----------------------------------------------------------------

  /**
   * Processes one simulation step of Broca's area.
   *
   * Biological basis:
   *   Broca's production cycle operates in ~150ms and consists of:
   *
   *   1. **Intention reception**: The input spikes represent
   *      the communicative intention of the prefrontal cortex, transmitted
   *      via fronto-frontal fibers.
   *
   *   2. **SNN processing**: The local neural network processes the intention
   *      through k-WTA competition, selecting the most relevant
   *      motor representations.
   *
   *   3. **Formulation**: The lexicon words that best capture the
   *      intention are selected (lexical access for production).
   *
   *   4. **Generation**: A sequence of speech motor patterns is
   *      produced and sent to the primary motor cortex for
   *      articulatory execution.
   *
   *   The emotional state is estimated from the spike activity
   *   in the absence of a direct input from the amygdala.
   *
   * @param spikes - Input spike vector (intention from the PFC)
   * @param modulationEffects - Current neuromodulation effects
   * @returns Output spike vector (speech motor patterns)
   */
  processInput(
    spikes: Float32Array,
    modulationEffects: ModulationEffects
  ): Float32Array {
    // 1. Compute activations of the local SNN
    const activations = new Float32Array(this.neuronCount);
    const inputLen = Math.min(spikes.length, this.inputCount);

    for (let n = 0; n < this.neuronCount; n++) {
      const baseOffset = n * this.inputCount;
      let sum = 0;

      for (let j = 0; j < inputLen; j++) {
        sum += this.weights[baseOffset + j] * spikes[j];
      }

      // Modulation: spike gain and attention
      sum *= modulationEffects.spikeGainMultiplier;

      // Simplified LIF integration
      this.potentials[n] += sum;
      this.potentials[n] *= 0.92; // Temporal leak (slightly faster than Wernicke)

      activations[n] = this.potentials[n];
    }

    // 2. k-WTA competition
    const k = Math.max(1, Math.floor(this.neuronCount * this.sparsity));
    const outputSpikes = new Float32Array(this.neuronCount);

    const sortedActivations = new Float32Array(activations);
    sortedActivations.sort();
    const kwtaThreshold = sortedActivations[this.neuronCount - k];

    for (let i = 0; i < this.neuronCount; i++) {
      if (activations[i] >= kwtaThreshold && activations[i] > ACTIVATION_FLOOR) {
        outputSpikes[i] = 1.0;
      }
    }

    // 3. Update spike state
    this.spikes.set(outputSpikes);

    // 4. Generate linguistic response from the spike pattern
    //    Estimate emotional state from neuromodulation:
    //    - High serotonin → positive valence; high cortisol → high arousal
    const estimatedEmotionalState: EmotionalState = {
      valence: (modulationEffects.spikeGainMultiplier - 1.0) * 0.5,
      arousal: Math.max(0, Math.min(1, (modulationEffects.attentionGain - 1.0) * 0.8)),
    };

    this.generateResponse(spikes, estimatedEmotionalState);

    // 5. Modulated Hebbian learning
    if (modulationEffects.learningRateMultiplier > 0) {
      this.hebbianUpdate(spikes, outputSpikes);
    }

    return outputSpikes;
  }

  /**
   * Hebbian update of synaptic weights for production.
   *
   * Biological basis:
   *   The synapses in the inferior frontal gyrus are strengthened when
   *   an intention pattern (pre) successfully activates a motor
   *   pattern (post). This refines the association between meaning and
   *   lexical form, improving production fluency with practice.
   *
   * @param preSpikes - Input spikes (prefrontal intention)
   * @param postSpikes - Output spikes (motor patterns)
   */
  private hebbianUpdate(preSpikes: Float32Array, postSpikes: Float32Array): void {
    const lr = this._modulatedLearningRate * 0.005;
    const inputLen = Math.min(preSpikes.length, this.inputCount);

    for (let n = 0; n < this.neuronCount; n++) {
      if (postSpikes[n] === 0) continue;

      const baseOffset = n * this.inputCount;
      for (let j = 0; j < inputLen; j++) {
        if (preSpikes[j] > 0) {
          this.weights[baseOffset + j] += lr * preSpikes[j];
        }

        // Weight clamp for stability
        if (this.weights[baseOffset + j] > 1.0) {
          this.weights[baseOffset + j] = 1.0;
        } else if (this.weights[baseOffset + j] < 0) {
          this.weights[baseOffset + j] = 0;
        }
      }
    }
  }
}
