/**
 * PREFRONTAL CORTEX — Executive Center of the Digital Brain
 * ==========================================================
 * Models the dorsolateral (dlPFC) and ventromedial (vmPFC) prefrontal cortex,
 * the center of the higher executive functions of the human brain.
 *
 * Biological basis:
 *   The prefrontal cortex occupies ~30% of the human neocortex and is the last
 *   region to mature (~25 years). It performs critical executive functions:
 *
 *   1. **Working memory** (dlPFC): Keeps information "online" for active
 *      manipulation. Limited to ~7±2 items (Miller, 1956) by the
 *      capacity to maintain sustained firing patterns in recurrent
 *      circuits. Each "slot" is a neural population that maintains a
 *      persistent activation pattern through recurrent excitation.
 *
 *   2. **Multimodal integration**: Receives afferents from ALL cortical
 *      areas (visual, auditory, somatosensory, limbic) and from the
 *      thalamus. It is the only region with such broad connectivity, which
 *      allows it to create unified representations of the global state.
 *
 *   3. **Top-down control**: Sends descending signals that modulate
 *      processing in sensory cortices and the thalamus, implementing
 *      selective attention and distractor suppression (Desimone & Duncan, 1995).
 *
 *   4. **Decision making**: Evaluation of options weighted by
 *      emotional information (vmPFC, Damasio's somatic markers) and
 *      expected reward (dopaminergic signals from the VTA).
 *
 * Implementation:
 *   - Working memory as an array of slots with pattern, label, age and priority
 *   - Integration via weighted superposition of inputs from multiple regions
 *   - Top-down signals as per-region attentional modulation vectors
 *   - Internal SNN with k-WTA for competitive selection
 */

import { BrainRegion } from '../../core/brain-region.js';
import type { ModulationEffects } from '../../core/neuromodulators/modulator-system.js';

/**
 * Activation floor for the k-WTA. Potentials are sums of dimensionless
 * weights (~0 at rest), not mV. At rest (no cortical drive) the
 * region stays at 0%; it only fires when there is a real signal above the floor.
 */
const ACTIVATION_FLOOR = 1e-3;

// ==================================================================
// Interfaces
// ==================================================================

/**
 * Working memory slot.
 *
 * Biological basis:
 *   Each slot corresponds to a neural assembly in the dlPFC that maintains
 *   a sustained firing pattern through recurrent excitation.
 *   The "age" models the natural decay of persistent activation
 *   in the absence of reactivation (working memory decay).
 */
export interface WorkingMemorySlot {
  /** Neural activation pattern actively maintained */
  pattern: Float32Array;
  /** Semantic label of the content (for debugging/introspection) */
  label: string;
  /** Age of the slot in simulation steps (decays over time) */
  age: number;
  /** Attentional priority (0.0–1.0). Determines resistance to eviction */
  priority: number;
}

/**
 * Top-down control signal generated by the prefrontal cortex.
 *
 * Biological basis:
 *   Descending prefrontal projections modulate the gain of
 *   neurons in sensory cortices (feature-based attention)
 *   and in the thalamus (attentional filter, attentional spotlight model).
 */
export interface TopDownSignal {
  /** Identifier of the target region */
  targetRegion: string;
  /** Attentional modulation vector for the target region */
  attentionMask: Float32Array;
  /** Global intensity of the signal (0.0–1.0) */
  gain: number;
}

/**
 * Result of the executive processing of a simulation step.
 */
export interface ExecutiveOutput {
  /** Output spikes of the prefrontal SNN */
  outputSpikes: Float32Array;
  /** Top-down signals generated for other regions */
  topDownSignals: TopDownSignal[];
  /** Current content of the working memory */
  workingMemorySnapshot: ReadonlyArray<Readonly<{ label: string; priority: number; age: number }>>;
}

// ==================================================================
// Clase PrefrontalCortex
// ==================================================================

/**
 * Prefrontal Cortex — Executive center of the digital brain.
 *
 * Integrates information from all regions, maintains representations
 * in working memory (7±2 slots), and generates top-down control signals
 * to modulate processing in sensory cortices and the thalamus.
 *
 * The internal SNN uses k-WTA (k-Winners-Take-All) competition to
 * select the most relevant representations and suppress distractors,
 * modeling the lateral inhibition mediated by GABAergic interneurons
 * of prefrontal layer III.
 */
export class PrefrontalCortex extends BrainRegion {
  /**
   * Working memory slots.
   *
   * Biology: Recurrent circuits in the dlPFC maintain sustained
   * firing patterns. The capacity is limited by the competition
   * between neural assemblies (~7±2 items, Miller 1956).
   */
  private workingMemory: WorkingMemorySlot[] = [];

  /**
   * Maximum capacity of the working memory.
   * Based on Miller's law (7±2): the magic number of items
   * that human working memory can hold simultaneously.
   */
  private readonly maxSlots: number = 7;

  /**
   * Decay rate of the working memory (per simulation step).
   *
   * Biology: Without reactivation, persistent activity in the dlPFC
   * decays in ~15-30 seconds (Peterson & Peterson, 1959).
   */
  private readonly decayRate: number = 0.02;

  /**
   * Last integrated representation of all inputs.
   * It is kept between steps to model the persistence of the
   * executive representation.
   */
  private integratedRepresentation: Float32Array;

  /**
   * Top-down signals generated in the last step.
   */
  private lastTopDownSignals: TopDownSignal[] = [];

  /**
   * Creates the Prefrontal Cortex of the digital brain.
   *
   * Biology: The human prefrontal cortex contains ~300 million neurons.
   * We model 15,000 neurons with 10,000 inputs, capturing the high
   * convergence of inputs that characterizes this region.
   */
  constructor(neuronCount: number = 15000, inputCount: number = 10000) {
    super(
      'prefrontalCortex',
      'Corteza Prefrontal — Centro Ejecutivo',
      neuronCount,
      inputCount
    );
    this.integratedRepresentation = new Float32Array(this.neuronCount);
  }

  // ----------------------------------------------------------------
  // Working Memory
  // ----------------------------------------------------------------

  /**
   * Attends to a pattern, entering it into working memory.
   *
   * Biological basis:
   *   When attending to a stimulus, prefrontal neurons form a
   *   persistent firing assembly that keeps the representation
   *   "online". If memory is full, the item with the
   *   lowest priority is evicted (competition between assemblies for limited
   *   neural resources, Cowan's capacity model, 2001).
   *
   * @param pattern - Neural pattern to hold in working memory
   * @param label - Semantic label of the pattern
   * @param priority - Attentional priority (0.0–1.0)
   */
  attendTo(pattern: Float32Array, label: string, priority: number): void {
    const clampedPriority = Math.max(0, Math.min(1, priority));

    // If a slot with the same label already exists, update instead of duplicating
    const existingIdx = this.workingMemory.findIndex(s => s.label === label);
    if (existingIdx >= 0) {
      const slot = this.workingMemory[existingIdx];
      slot.pattern = new Float32Array(pattern);
      slot.priority = clampedPriority;
      slot.age = 0; // Reactivating refreshes the slot
      return;
    }

    // If memory is full, evict the slot with the lowest priority
    if (this.workingMemory.length >= this.maxSlots) {
      this.evictLowestPriority();
    }

    this.workingMemory.push({
      pattern: new Float32Array(pattern),
      label,
      age: 0,
      priority: clampedPriority,
    });
  }

  /**
   * Evicts the slot with the lowest priority from working memory.
   *
   * Biology: When attentional resources are saturated, the least
   * relevant items lose their sustained activation and are displaced
   * by new information (proactive/retroactive interference).
   */
  private evictLowestPriority(): void {
    if (this.workingMemory.length === 0) return;

    let minIdx = 0;
    let minScore = Infinity;

    for (let i = 0; i < this.workingMemory.length; i++) {
      // Combined score: low priority + high age → more likely eviction
      const slot = this.workingMemory[i];
      const score = slot.priority - slot.age * this.decayRate;
      if (score < minScore) {
        minScore = score;
        minIdx = i;
      }
    }

    this.workingMemory.splice(minIdx, 1);
  }

  /**
   * Ages all working memory slots and removes the decayed ones.
   *
   * Biology: Without rehearsal (active review), persistent activity
   * decays exponentially. Items whose activation falls below
   * a threshold stop being consciously accessible.
   */
  private ageWorkingMemory(): void {
    for (const slot of this.workingMemory) {
      slot.age++;
      // Gradually reduce priority with age
      slot.priority *= (1 - this.decayRate);
    }

    // Remove slots whose priority has decayed below a minimum threshold
    this.workingMemory = this.workingMemory.filter(s => s.priority > 0.01);
  }

  /**
   * Returns the current content of the working memory.
   *
   * @returns Read-only copy of the current slots
   */
  getWorkingMemory(): ReadonlyArray<Readonly<WorkingMemorySlot>> {
    return this.workingMemory;
  }

  // ----------------------------------------------------------------
  // Multimodal Integration
  // ----------------------------------------------------------------

  /**
   * Integrates signals from multiple brain regions into a unified representation.
   *
   * Biological basis:
   *   The prefrontal cortex receives convergent projections from all
   *   sensory, motor, limbic cortical areas and from the thalamus.
   *   Integration occurs through weighted superposition of activation
   *   patterns, where the weight reflects the current attentional relevance
   *   of each source (biased competition attention, Desimone & Duncan 1995).
   *
   *   The result is a "global workspace" representation (Baars, 1988)
   *   that captures the integrated state of the system's cognition.
   *
   * @param inputs - Map of regionId → output spikes of each region
   * @returns Integrated representation as a Float32Array
   */
  integrate(inputs: Map<string, Float32Array>): Float32Array {
    const integrated = new Float32Array(this.neuronCount);

    if (inputs.size === 0) return integrated;

    const invCount = 1.0 / inputs.size;

    for (const [, regionSpikes] of inputs) {
      // Project each region's spikes into the prefrontal space
      // using the synaptic weights as a projection matrix
      const projectionLen = Math.min(regionSpikes.length, this.inputCount);

      for (let n = 0; n < this.neuronCount; n++) {
        const baseOffset = n * this.inputCount;
        let activation = 0;

        for (let j = 0; j < projectionLen; j++) {
          activation += this.weights[baseOffset + j] * regionSpikes[j];
        }

        integrated[n] += activation * invCount;
      }
    }

    return integrated;
  }

  // ----------------------------------------------------------------
  // Top-Down Signals
  // ----------------------------------------------------------------

  /**
   * Generates a top-down control signal for a target region.
   *
   * Biological basis:
   *   The PFC's descending projections modulate the gain of
   *   neurons in the sensory cortices and the thalamus. This modulation
   *   implements selective attention: it amplifies relevant signals and
   *   suppresses distractors (Desimone & Duncan's attentional bias model).
   *
   *   The biological mechanism involves:
   *   - Glutamatergic projections from prefrontal layers II/III
   *   - To pyramidal neurons and interneurons in the target cortex
   *   - Resulting in (multiplicative) gain increase for
   *     attended stimuli
   *
   * @param targetRegion - Identifier of the region to modulate
   * @returns Top-down signal with attentional mask and gain
   */
  generateTopDownSignal(targetRegion: string): TopDownSignal {
    // Generate the attentional mask based on the current integrated state
    // and the content of the working memory
    const maskSize = this.inputCount;
    const attentionMask = new Float32Array(maskSize);

    // The mask is built from the patterns in working memory
    // Biology: attention amplifies the features that match
    // the representations held in working memory
    let totalPriority = 0;
    for (const slot of this.workingMemory) {
      totalPriority += slot.priority;
    }

    if (totalPriority > 0) {
      const invTotal = 1.0 / totalPriority;
      for (const slot of this.workingMemory) {
        const weight = slot.priority * invTotal;
        const len = Math.min(slot.pattern.length, maskSize);
        for (let i = 0; i < len; i++) {
          attentionMask[i] += slot.pattern[i] * weight;
        }
      }
    }

    // Normalize the mask to the range [0, 1]
    let maxVal = 0;
    for (let i = 0; i < maskSize; i++) {
      if (attentionMask[i] > maxVal) maxVal = attentionMask[i];
    }
    if (maxVal > 0) {
      const invMax = 1.0 / maxVal;
      for (let i = 0; i < maskSize; i++) {
        attentionMask[i] *= invMax;
      }
    }

    // The gain depends on the current prefrontal activity
    // (more activity → stronger top-down signal)
    let activeCount = 0;
    for (let i = 0; i < this.spikes.length; i++) {
      if (this.spikes[i] > 0) activeCount++;
    }
    const gain = Math.min(1.0, activeCount / (this.neuronCount * this.sparsity + 1));

    return {
      targetRegion,
      attentionMask,
      gain,
    };
  }

  /**
   * Returns the top-down signals generated in the last step.
   */
  getLastTopDownSignals(): ReadonlyArray<Readonly<TopDownSignal>> {
    return this.lastTopDownSignals;
  }

  // ----------------------------------------------------------------
  // k-WTA (k-Winners Take All) — Neural competition
  // ----------------------------------------------------------------

  /**
   * Applies k-WTA competitive selection to the activation vector.
   *
   * Biological basis:
   *   The lateral inhibition mediated by GABAergic interneurons in
   *   layer III of the prefrontal cortex implements a
   *   "winner-take-all" competition (Winner-Take-All). Only the k neurons
   *   with the highest activation fire, the rest are suppressed.
   *   The value of k is controlled by the sparsity (modulated by
   *   neuromodulators such as norepinephrine and acetylcholine).
   *
   * @param activations - Pre-competition activation vector
   * @returns Post-competition spike vector (sparse)
   */
  private applyKWTA(activations: Float32Array): Float32Array {
    const output = new Float32Array(activations.length);
    const k = Math.max(1, Math.floor(activations.length * this.sparsity));

    // Find the k-th highest value (competition threshold)
    // We use partial selection for O(n) efficiency
    const sorted = new Float32Array(activations);
    sorted.sort();
    const threshold = sorted[sorted.length - k];

    // Only neurons above the threshold fire
    for (let i = 0; i < activations.length; i++) {
      if (activations[i] >= threshold && activations[i] > ACTIVATION_FLOOR) {
        output[i] = 1.0;
      }
    }

    return output;
  }

  // ----------------------------------------------------------------
  // processInput — Main executive cycle
  // ----------------------------------------------------------------

  /**
   * Processes a simulation step of the prefrontal cortex.
   *
   * Biological basis:
   *   The prefrontal executive cycle occurs in ~100ms (theta rhythm, 4-8 Hz)
   *   and consists of:
   *
   *   1. **Reception**: Integrate afferents from all regions
   *   2. **Maintenance**: Update the working memory (age,
   *      refresh relevant items, evict irrelevant items)
   *   3. **Competition**: k-WTA over activations to select
   *      the most relevant representations
   *   4. **Control**: Generate top-down signals to modulate processing
   *      in sensory regions and the thalamus
   *
   * @param spikes - Input spike vector (integrated from the sensory buffer)
   * @param modulationEffects - Current neuromodulation effects
   * @returns Output spike vector (executive representation)
   */
  processInput(
    spikes: Float32Array,
    modulationEffects: ModulationEffects
  ): Float32Array {
    // 1. Compute activations of the local SNN
    //    Each prefrontal neuron integrates the inputs weighted by its synaptic weights
    const activations = new Float32Array(this.neuronCount);
    const inputLen = Math.min(spikes.length, this.inputCount);

    for (let n = 0; n < this.neuronCount; n++) {
      const baseOffset = n * this.inputCount;
      let sum = 0;

      for (let j = 0; j < inputLen; j++) {
        sum += this.weights[baseOffset + j] * spikes[j];
      }

      // Apply neuromodulation gain and modulated threshold
      sum *= modulationEffects.spikeGainMultiplier;

      // Simplified LIF model: integrate into the membrane potential
      this.potentials[n] += sum;
      this.potentials[n] *= 0.95; // Leak (membrane leak)

      // The potential is a sum of dimensionless weights (~0 at rest), not mV.
      // Subtracting _modulatedThreshold (−55 mV) shifted it by +55 and the `>0` gate of
      // the k-WTA always passed → constant and false activity. The raw potential
      // is used and the k-WTA filters against a real floor.
      activations[n] = this.potentials[n];
    }

    // 2. k-WTA competitive selection
    const outputSpikes = this.applyKWTA(activations);

    // 3. Update spike state
    this.spikes.set(outputSpikes);

    // 4. Maintain the integrated representation (with decay)
    for (let i = 0; i < this.neuronCount; i++) {
      this.integratedRepresentation[i] =
        this.integratedRepresentation[i] * 0.8 + outputSpikes[i] * 0.2;
    }

    // 5. Age the working memory
    this.ageWorkingMemory();

    // 6. Dopamine-modulated Hebbian learning
    //    "Neurons that fire together wire together" (Hebb, 1949)
    if (modulationEffects.learningRateMultiplier > 0) {
      this.hebbianUpdate(spikes, outputSpikes, modulationEffects);
    }

    return outputSpikes;
  }

  /**
   * Hebbian update of synaptic weights.
   *
   * Biological basis:
   *   Synaptic plasticity in the prefrontal cortex is strongly
   *   modulated by dopamine (reward/prediction-error signal).
   *   Synapses between neurons that fire together strengthen (LTP),
   *   while the rest weaken (LTD). Dopamine acts as
   *   a "gate" that determines whether the strengthening is consolidated
   *   (three-factor learning rule: pre × post × modulation).
   *
   * @param preSpikes - Presynaptic spikes (inputs)
   * @param postSpikes - Postsynaptic spikes (k-WTA output)
   * @param modulation - Neuromodulation effects (includes learningRate)
   */
  private hebbianUpdate(
    preSpikes: Float32Array,
    postSpikes: Float32Array,
    modulation: ModulationEffects
  ): void {
    const lr = this._modulatedLearningRate * 0.01; // Scale for stability
    const inputLen = Math.min(preSpikes.length, this.inputCount);

    for (let n = 0; n < this.neuronCount; n++) {
      if (postSpikes[n] === 0) continue; // Only update active neurons

      const baseOffset = n * this.inputCount;
      for (let j = 0; j < inputLen; j++) {
        if (preSpikes[j] > 0) {
          // LTP: strengthen active pre→post connection
          this.weights[baseOffset + j] += lr * preSpikes[j] * postSpikes[n];
        } else {
          // Soft LTD: weaken unused connections
          this.weights[baseOffset + j] *= (1 - lr * 0.1);
        }

        // Clamp weights for stability
        if (this.weights[baseOffset + j] > 1.0) {
          this.weights[baseOffset + j] = 1.0;
        } else if (this.weights[baseOffset + j] < 0) {
          this.weights[baseOffset + j] = 0;
        }
      }
    }
  }
}
